"""
Nginx Templates - Hardened, Production-Ready Configurations

Supports:
- WebSocket proxy locations
- Multiple upstream proxy paths (e.g., /api/ → port 8000)
- Optional HTTP Basic Auth
- Gzip, security headers, SSL hardening
"""

# ═══════════════════════════════════════════════════════════════════════════════
# COMMON SNIPPETS
# ═══════════════════════════════════════════════════════════════════════════════

SECURITY_HEADERS = """
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
"""

GZIP_CONFIG = """
    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;
"""

SSL_CONFIG = """
    # SSL Configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;
    ssl_stapling on;
    ssl_stapling_verify on;
"""

RATE_LIMIT_ZONE = """
# Rate limiting zone (put in http block or nginx.conf)
# limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
# limit_req_zone $binary_remote_addr zone=login:10m rate=1r/s;
"""

# ─────────────────────────────────────────────────────────────────────────────
# Reusable Jinja2 blocks injected into every Node.js/proxy template
# ─────────────────────────────────────────────────────────────────────────────

# Extra proxy location blocks (REST API upstreams)
PROXY_PATHS_BLOCK = """
{% if proxy_paths %}
{% for pp in proxy_paths %}
    # ── Proxy: {{ pp.path }} → :{{ pp.port }} {{ '(' + pp.description + ')' if pp.description else '' }}
    location {{ pp.path }} {
        proxy_pass         http://127.0.0.1:{{ pp.port }}/;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;

        # Timeouts
        proxy_read_timeout  300s;
        proxy_send_timeout  300s;
    }

{% endfor %}
{% endif %}
"""

# WebSocket location blocks
WS_PATHS_BLOCK = """
{% if ws_paths %}
{% for ws in ws_paths %}
    # ── WebSocket: {{ ws.path }} → :{{ ws.port }}{{ ws.upstream_path }} {{ '(' + ws.description + ')' if ws.description else '' }}
    location {{ ws.path }} {
        proxy_pass         http://127.0.0.1:{{ ws.port }}{{ ws.upstream_path }};
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host       $host;
        proxy_set_header   X-Real-IP  $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;

        # WebSocket keepalive
        proxy_read_timeout  86400s;
        proxy_send_timeout  86400s;
    }

{% endfor %}
{% endif %}
"""

# Basic auth snippet (applied globally to the server block)
BASIC_AUTH_BLOCK = """
{% if basic_auth %}
    # HTTP Basic Authentication
    auth_basic           "{{ basic_auth_realm | default('Restricted Access') }}";
    auth_basic_user_file /etc/nginx/.htpasswd-{{ domain }};
{% endif %}
"""


# ═══════════════════════════════════════════════════════════════════════════════
# NEXT.JS / NUXT.JS TEMPLATE (Hardened)
# ═══════════════════════════════════════════════════════════════════════════════

NODEJS_TEMPLATE = """# {{ domain }} - Node.js Application (Next.js/Nuxt.js)
# Generated by Forge CLI - Hardened Configuration
# Last updated: {{ generated_at }}

{% if upstream_name is defined %}
upstream {{ upstream_name }} {
    server 127.0.0.1:{{ port }};
    keepalive 64;
}
{% endif %}

server {
    listen 80;
    listen [::]:80;
    server_name {{ domain }}{% if www %} www.{{ domain }}{% endif %};

    # Redirect to HTTPS (uncomment after SSL is configured)
    # return 301 https://$server_name$request_uri;

    # Request limits
    client_max_body_size {{ max_body_size | default('100M') }};
    client_body_timeout {{ body_timeout | default('60s') }};
    client_header_timeout {{ header_timeout | default('60s') }};

    # Proxy timeouts
    proxy_connect_timeout {{ proxy_connect_timeout | default('60s') }};
    proxy_send_timeout {{ proxy_send_timeout | default('60s') }};
    proxy_read_timeout {{ proxy_read_timeout | default('300s') }};
{{ security_headers }}
{{ gzip_config }}
{{ basic_auth_block }}
    # Logging
    access_log /var/log/nginx/{{ domain }}.access.log;
    error_log /var/log/nginx/{{ domain }}.error.log;

    location / {
        proxy_pass http://127.0.0.1:{{ port }};
        proxy_http_version 1.1;

        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';

        # Headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;

        # Buffer settings
        proxy_buffering on;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;

        proxy_cache_bypass $http_upgrade;
    }
{{ extra_proxy_blocks }}
{{ ws_blocks }}
    # Static assets with caching
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        proxy_pass http://127.0.0.1:{{ port }};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    # Health check endpoint
    location = /health {
        access_log off;
        proxy_pass http://127.0.0.1:{{ port }};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Block hidden files
    location ~ /\\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
"""

# ═══════════════════════════════════════════════════════════════════════════════
# PHP / LARAVEL TEMPLATE (Hardened)
# ═══════════════════════════════════════════════════════════════════════════════

PHP_TEMPLATE = """# {{ domain }} - PHP Application (Laravel)
# Generated by Forge CLI - Hardened Configuration
# Last updated: {{ generated_at }}

server {
    listen 80;
    listen [::]:80;
    server_name {{ domain }}{% if www %} www.{{ domain }}{% endif %};

    root {{ document_root }};
    index index.php index.html index.htm;

    # Request limits
    client_max_body_size {{ max_body_size | default('100M') }};
    client_body_timeout {{ body_timeout | default('60s') }};
    client_header_timeout {{ header_timeout | default('60s') }};

    # FastCGI timeouts
    fastcgi_connect_timeout {{ fastcgi_connect_timeout | default('60s') }};
    fastcgi_send_timeout {{ fastcgi_send_timeout | default('60s') }};
    fastcgi_read_timeout {{ fastcgi_read_timeout | default('300s') }};
{{ security_headers }}
{{ gzip_config }}
{{ basic_auth_block }}
    # Logging
    access_log /var/log/nginx/{{ domain }}.access.log;
    error_log /var/log/nginx/{{ domain }}.error.log;

    # Laravel routing
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM handling
    location ~ \\.php$ {
        fastcgi_pass unix:/var/run/php/php{{ php_version }}-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;

        # Buffer settings
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;

        # Intercept errors for custom error pages
        fastcgi_intercept_errors off;
    }

    # Block hidden files (except .well-known for SSL)
    location ~ /\\.(?!well-known).* {
        deny all;
        access_log off;
        log_not_found off;
    }

    # Block sensitive files
    location ~* (?:composer\\.json|composer\\.lock|package\\.json|package-lock\\.json|\\.env|\\.git) {
        deny all;
        access_log off;
        log_not_found off;
    }

    # Static assets caching
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # Deny access to uploads with php
    location ~* /(?:uploads|files)/.*\\.php$ {
        deny all;
    }
}
"""

# ═══════════════════════════════════════════════════════════════════════════════
# STATIC SITE TEMPLATE (Hardened)
# ═══════════════════════════════════════════════════════════════════════════════

STATIC_TEMPLATE = """# {{ domain }} - Static Website
# Generated by Forge CLI - Hardened Configuration
# Last updated: {{ generated_at }}

server {
    listen 80;
    listen [::]:80;
    server_name {{ domain }}{% if www %} www.{{ domain }}{% endif %};

    root {{ document_root }};
    index index.html index.htm;

    # Request limits
    client_max_body_size {{ max_body_size | default('10M') }};
    client_body_timeout {{ body_timeout | default('30s') }};
    client_header_timeout {{ header_timeout | default('30s') }};
{{ security_headers }}
{{ gzip_config }}
{{ basic_auth_block }}
    # Logging
    access_log /var/log/nginx/{{ domain }}.access.log;
    error_log /var/log/nginx/{{ domain }}.error.log;

    location / {
        try_files $uri $uri/ =404;
    }

    # Static assets with long cache
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # Block hidden files (except .well-known for SSL)
    location ~ /\\.(?!well-known).* {
        deny all;
        access_log off;
        log_not_found off;
    }

    # Custom error pages
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
        internal;
    }
}
"""

# ═══════════════════════════════════════════════════════════════════════════════
# SSL ENABLED TEMPLATES (HTTPS)
# ═══════════════════════════════════════════════════════════════════════════════

NODEJS_TEMPLATE_SSL = """# {{ domain }} - Node.js Application (Next.js/Nuxt.js) with SSL
# Generated by Forge CLI - Hardened Configuration
# Last updated: {{ generated_at }}

# HTTP to HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name {{ domain }}{% if www %} www.{{ domain }}{% endif %};
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {{ domain }}{% if www %} www.{{ domain }}{% endif %};

    # SSL certificates
    ssl_certificate /etc/letsencrypt/live/{{ domain }}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{ domain }}/privkey.pem;
{{ ssl_config }}
    # HSTS (uncomment after testing)
    # add_header Strict-Transport-Security "max-age=63072000" always;

    # Request limits
    client_max_body_size {{ max_body_size | default('100M') }};
    client_body_timeout {{ body_timeout | default('60s') }};
    client_header_timeout {{ header_timeout | default('60s') }};

    # Proxy timeouts
    proxy_connect_timeout {{ proxy_connect_timeout | default('60s') }};
    proxy_send_timeout {{ proxy_send_timeout | default('60s') }};
    proxy_read_timeout {{ proxy_read_timeout | default('300s') }};
{{ security_headers }}
{{ gzip_config }}
{{ basic_auth_block }}
    # Logging
    access_log /var/log/nginx/{{ domain }}.access.log;
    error_log /var/log/nginx/{{ domain }}.error.log;

    location / {
        proxy_pass http://127.0.0.1:{{ port }};
        proxy_http_version 1.1;

        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';

        # Headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;

        # Buffer settings
        proxy_buffering on;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;

        proxy_cache_bypass $http_upgrade;
    }
{{ extra_proxy_blocks }}
{{ ws_blocks }}
    # Static assets with caching
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        proxy_pass http://127.0.0.1:{{ port }};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    # Block hidden files
    location ~ /\\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
"""

PHP_TEMPLATE_SSL = """# {{ domain }} - PHP Application (Laravel) with SSL
# Generated by Forge CLI - Hardened Configuration
# Last updated: {{ generated_at }}

# HTTP to HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name {{ domain }}{% if www %} www.{{ domain }}{% endif %};
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {{ domain }}{% if www %} www.{{ domain }}{% endif %};

    root {{ document_root }};
    index index.php index.html index.htm;

    # SSL certificates
    ssl_certificate /etc/letsencrypt/live/{{ domain }}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{ domain }}/privkey.pem;
{{ ssl_config }}
    # Request limits
    client_max_body_size {{ max_body_size | default('100M') }};
    client_body_timeout {{ body_timeout | default('60s') }};
    client_header_timeout {{ header_timeout | default('60s') }};

    # FastCGI timeouts
    fastcgi_connect_timeout {{ fastcgi_connect_timeout | default('60s') }};
    fastcgi_send_timeout {{ fastcgi_send_timeout | default('60s') }};
    fastcgi_read_timeout {{ fastcgi_read_timeout | default('300s') }};
{{ security_headers }}
{{ gzip_config }}
{{ basic_auth_block }}
    # Logging
    access_log /var/log/nginx/{{ domain }}.access.log;
    error_log /var/log/nginx/{{ domain }}.error.log;

    # Laravel routing
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM handling
    location ~ \\.php$ {
        fastcgi_pass unix:/var/run/php/php{{ php_version }}-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;

        # Buffer settings
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
    }

    # Block hidden files (except .well-known for SSL)
    location ~ /\\.(?!well-known).* {
        deny all;
    }

    # Block sensitive files
    location ~* (?:composer\\.json|composer\\.lock|package\\.json|package-lock\\.json|\\.env|\\.git) {
        deny all;
    }

    # Static assets caching
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }
}
"""

# ═══════════════════════════════════════════════════════════════════════════════
# TEMPLATE RENDERING
# ═══════════════════════════════════════════════════════════════════════════════

from datetime import datetime
from typing import Optional
from jinja2 import Template


def _render_snippet(template_str: str, context: dict) -> str:
    """Render a Jinja2 snippet with the given context."""
    return Template(template_str).render(**context)


def render_template(
    site_type: str,
    domain: str,
    www: bool = True,
    port: int = 3000,
    document_root: Optional[str] = None,
    php_version: str = "8.3",
    ssl_enabled: bool = False,
    max_body_size: str = "100M",
    proxy_paths: Optional[list] = None,
    ws_paths: Optional[list] = None,
    basic_auth: bool = False,
    basic_auth_realm: str = "Restricted Access",
    **kwargs
) -> str:
    """
    Render an Nginx configuration template.

    Args:
        site_type:        One of 'nextjs', 'nuxt', 'php', 'static'.
        domain:           Primary domain (e.g., trading.example.com).
        www:              Include www. alias?
        port:             Primary upstream port.
        document_root:    Document root for PHP / static sites.
        php_version:      PHP-FPM version string.
        ssl_enabled:      Whether to use the SSL template variant.
        max_body_size:    client_max_body_size value.
        proxy_paths:      List of dicts with 'path', 'port', and optional 'description'.
                          Example: [{"path": "/api/", "port": 8000, "description": "REST API"}]
        ws_paths:         List of dicts with 'path', 'port', 'upstream_path', and optional 'description'.
                          Example: [{"path": "/ws", "port": 8000, "upstream_path": "/ws", "description": "WebSocket"}]
        basic_auth:       Enable HTTP Basic Authentication.
        basic_auth_realm: Auth realm message shown to the user.
    """

    # Select template based on type and SSL
    templates = {
        ("nextjs", False): NODEJS_TEMPLATE,
        ("nextjs", True): NODEJS_TEMPLATE_SSL,
        ("nuxt", False): NODEJS_TEMPLATE,
        ("nuxt", True): NODEJS_TEMPLATE_SSL,
        ("php", False): PHP_TEMPLATE,
        ("php", True): PHP_TEMPLATE_SSL,
        ("static", False): STATIC_TEMPLATE,
        ("static", True): STATIC_TEMPLATE,  # Static doesn't need special SSL template
    }

    template_str = templates.get((site_type, ssl_enabled), NODEJS_TEMPLATE)

    # Pre-render sub-blocks so Jinja2 context stays flat
    sub_context = {
        "domain": domain,
        "proxy_paths": proxy_paths or [],
        "ws_paths": ws_paths or [],
        "basic_auth": basic_auth,
        "basic_auth_realm": basic_auth_realm,
    }

    extra_proxy_rendered = _render_snippet(PROXY_PATHS_BLOCK, sub_context)
    ws_rendered = _render_snippet(WS_PATHS_BLOCK, sub_context)
    auth_rendered = _render_snippet(BASIC_AUTH_BLOCK, sub_context)

    # Build context
    context = {
        "domain": domain,
        "www": www,
        "port": port,
        "document_root": document_root or f"/var/www/{domain}",
        "php_version": php_version,
        "max_body_size": max_body_size,
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "security_headers": SECURITY_HEADERS,
        "gzip_config": GZIP_CONFIG,
        "ssl_config": SSL_CONFIG if ssl_enabled else "",
        "extra_proxy_blocks": extra_proxy_rendered,
        "ws_blocks": ws_rendered,
        "basic_auth_block": auth_rendered,
        **kwargs
    }

    return Template(template_str).render(**context)


def get_template_types() -> list:
    """Return available template types."""
    return [
        {"name": "⚡ Next.js", "value": "nextjs", "description": "Node.js reverse proxy"},
        {"name": "🟢 Nuxt.js", "value": "nuxt", "description": "Node.js reverse proxy"},
        {"name": "🐘 PHP / Laravel", "value": "php", "description": "PHP-FPM with optimizations"},
        {"name": "📄 Static HTML", "value": "static", "description": "Direct file serving"},
    ]
