"""
Site Management - Create and manage Nginx sites
"""

import os
import questionary
from rich.console import Console
from rich.table import Table
from rich import box
from jinja2 import Template

from utils.ui import (
    clear_screen, print_header, print_breadcrumb,
    print_success, print_error, print_warning, confirm_action
)
from utils.shell import run_command, get_command_output

console = Console()

SITES_AVAILABLE = "/etc/nginx/sites-available"
SITES_ENABLED = "/etc/nginx/sites-enabled"

# ═══════════════════════════════════════════════════════════════════════════════
# NGINX CONFIG TEMPLATES
# ═══════════════════════════════════════════════════════════════════════════════

NEXTJS_TEMPLATE = """# {{ domain }} - Next.js Application
# Generated by Forge CLI

server {
    listen 80;
    listen [::]:80;
    server_name {{ domain }}{% if www %} www.{{ domain }}{% endif %};

    location / {
        proxy_pass http://127.0.0.1:{{ port }};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}
"""

NUXT_TEMPLATE = """# {{ domain }} - Nuxt.js Application
# Generated by Forge CLI

server {
    listen 80;
    listen [::]:80;
    server_name {{ domain }}{% if www %} www.{{ domain }}{% endif %};

    location / {
        proxy_pass http://127.0.0.1:{{ port }};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}
"""

PHP_TEMPLATE = """# {{ domain }} - PHP Application
# Generated by Forge CLI

server {
    listen 80;
    listen [::]:80;
    server_name {{ domain }}{% if www %} www.{{ domain }}{% endif %};

    root {{ document_root }};
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \\.php$ {
        fastcgi_pass unix:/var/run/php/php{{ php_version }}-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\\.(?!well-known).* {
        deny all;
    }
}
"""

STATIC_TEMPLATE = """# {{ domain }} - Static Site
# Generated by Forge CLI

server {
    listen 80;
    listen [::]:80;
    server_name {{ domain }}{% if www %} www.{{ domain }}{% endif %};

    root {{ document_root }};
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ /\\.(?!well-known).* {
        deny all;
    }
}
"""

# ═══════════════════════════════════════════════════════════════════════════════
# SITES MENU
# ═══════════════════════════════════════════════════════════════════════════════

SITES_MENU_CHOICES = [
    {"name": "📋  List Sites", "value": "list"},
    {"name": "➕  Create Site", "value": "create"},
    {"name": "🗑️   Delete Site", "value": "delete"},
    {"name": "🔄  Enable/Disable Site", "value": "toggle"},
    questionary.Separator("─" * 30),
    {"name": "⬅️   Back", "value": "back"},
]


def run_sites_menu():
    """Display the sites management menu."""
    while True:
        clear_screen()
        print_header()
        print_breadcrumb(["Main", "Manage Sites"])

        choice = questionary.select(
            "Site Management:",
            choices=SITES_MENU_CHOICES,
            qmark="🌐",
            pointer="▶",
        ).ask()

        if choice is None or choice == "back":
            return

        if choice == "list":
            list_sites()
        elif choice == "create":
            create_site()
        elif choice == "delete":
            delete_site()
        elif choice == "toggle":
            toggle_site()


def list_sites():
    """List all Nginx sites."""
    clear_screen()
    print_header()
    print_breadcrumb(["Main", "Manage Sites", "List"])

    # Get available sites
    code, stdout, _ = run_command(f"ls {SITES_AVAILABLE}", check=False)
    available = stdout.split() if code == 0 else []

    # Get enabled sites
    code, stdout, _ = run_command(f"ls {SITES_ENABLED}", check=False)
    enabled = stdout.split() if code == 0 else []

    if not available:
        print_warning("No sites found.")
    else:
        table = Table(
            title="🌐 Nginx Sites",
            box=box.ROUNDED,
            header_style="bold magenta",
        )
        table.add_column("Site", style="cyan")
        table.add_column("Status", justify="center")

        for site in available:
            if site == "default":
                continue
            status = "🟢 Enabled" if site in enabled else "⚪ Disabled"
            table.add_row(site, status)

        console.print(table)

    console.print()
    questionary.press_any_key_to_continue().ask()


def create_site():
    """Create a new site interactively."""
    clear_screen()
    print_header()
    print_breadcrumb(["Main", "Manage Sites", "Create"])

    # Select site type
    site_type = questionary.select(
        "Select site type:",
        choices=[
            {"name": "⚡ Next.js", "value": "nextjs"},
            {"name": "🟢 Nuxt.js", "value": "nuxt"},
            {"name": "🐘 PHP / Laravel", "value": "php"},
            {"name": "📄 Static HTML", "value": "static"},
        ],
        qmark="🌐",
    ).ask()

    if not site_type:
        return

    # Get domain name
    domain = questionary.text(
        "Enter domain name (e.g., example.com):",
        validate=lambda x: len(x) > 0 and "." in x,
    ).ask()

    if not domain:
        return

    # Include www?
    include_www = questionary.confirm(
        f"Include www.{domain}?",
        default=True,
    ).ask()

    # Type-specific configuration
    config = {"domain": domain, "www": include_www}

    if site_type in ["nextjs", "nuxt"]:
        port = questionary.text(
            "Enter application port:",
            default="3000",
            validate=lambda x: x.isdigit() and 1000 <= int(x) <= 65535,
        ).ask()
        config["port"] = port
        template = NEXTJS_TEMPLATE if site_type == "nextjs" else NUXT_TEMPLATE

    elif site_type == "php":
        doc_root = questionary.text(
            "Enter document root path:",
            default=f"/var/www/{domain}/public",
        ).ask()
        php_version = questionary.select(
            "Select PHP version:",
            choices=["8.3", "8.2", "8.1", "8.0"],
        ).ask()
        config["document_root"] = doc_root
        config["php_version"] = php_version
        template = PHP_TEMPLATE

    else:  # static
        doc_root = questionary.text(
            "Enter document root path:",
            default=f"/var/www/{domain}",
        ).ask()
        config["document_root"] = doc_root
        template = STATIC_TEMPLATE

    # Generate config
    rendered = Template(template).render(**config)

    console.print("\n[bold]Generated Configuration:[/bold]")
    console.print(f"[dim]{rendered}[/dim]")

    if not confirm_action("Create this site?", default=True):
        return

    # Write config file
    config_path = f"{SITES_AVAILABLE}/{domain}"

    # Write to temp file first, then move with sudo
    temp_path = f"/tmp/{domain}.conf"
    with open(temp_path, "w") as f:
        f.write(rendered)

    run_command(f"sudo mv {temp_path} {config_path}", check=False)

    # Enable site
    run_command(f"sudo ln -sf {config_path} {SITES_ENABLED}/{domain}", check=False)

    # Test and reload nginx
    code, _, stderr = run_command("sudo nginx -t", check=False)
    if code != 0:
        print_error(f"Nginx config test failed: {stderr}")
        return

    run_command("sudo systemctl reload nginx", check=False)

    print_success(f"Site {domain} created and enabled!")

    # Ask about SSL
    if questionary.confirm("Would you like to set up SSL?", default=True).ask():
        from sslcerts import provision_ssl_for_domain
        provision_ssl_for_domain(domain, include_www)

    questionary.press_any_key_to_continue().ask()


def delete_site():
    """Delete a site."""
    clear_screen()
    print_header()
    print_breadcrumb(["Main", "Manage Sites", "Delete"])

    # Get available sites
    code, stdout, _ = run_command(f"ls {SITES_AVAILABLE}", check=False)
    sites = [s for s in stdout.split() if s != "default"] if code == 0 else []

    if not sites:
        print_warning("No sites to delete.")
        questionary.press_any_key_to_continue().ask()
        return

    site = questionary.select(
        "Select site to delete:",
        choices=sites + [questionary.Separator(), {"name": "⬅️ Cancel", "value": None}],
    ).ask()

    if not site:
        return

    if not confirm_action(f"Are you sure you want to delete {site}? This cannot be undone."):
        return

    # Remove from sites-enabled and sites-available
    run_command(f"sudo rm -f {SITES_ENABLED}/{site}", check=False)
    run_command(f"sudo rm -f {SITES_AVAILABLE}/{site}", check=False)
    run_command("sudo systemctl reload nginx", check=False)

    print_success(f"Site {site} deleted!")
    questionary.press_any_key_to_continue().ask()


def toggle_site():
    """Enable or disable a site."""
    clear_screen()
    print_header()
    print_breadcrumb(["Main", "Manage Sites", "Toggle"])

    # Get available sites
    code, stdout, _ = run_command(f"ls {SITES_AVAILABLE}", check=False)
    available = [s for s in stdout.split() if s != "default"] if code == 0 else []

    code, stdout, _ = run_command(f"ls {SITES_ENABLED}", check=False)
    enabled = stdout.split() if code == 0 else []

    if not available:
        print_warning("No sites found.")
        questionary.press_any_key_to_continue().ask()
        return

    choices = []
    for site in available:
        status = "🟢" if site in enabled else "⚪"
        choices.append({"name": f"{status} {site}", "value": site})

    choices.append(questionary.Separator())
    choices.append({"name": "⬅️ Cancel", "value": None})

    site = questionary.select(
        "Select site to toggle:",
        choices=choices,
    ).ask()

    if not site:
        return

    if site in enabled:
        # Disable
        run_command(f"sudo rm -f {SITES_ENABLED}/{site}", check=False)
        print_success(f"Site {site} disabled.")
    else:
        # Enable
        run_command(f"sudo ln -sf {SITES_AVAILABLE}/{site} {SITES_ENABLED}/{site}", check=False)
        print_success(f"Site {site} enabled.")

    run_command("sudo systemctl reload nginx", check=False)
    questionary.press_any_key_to_continue().ask()
